apiVersion: v1
kind: Service
metadata:
  name: web-user-lb
  annotations:
    loadBalancerIP: "34.111.211.192"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: web-user
  