apiVersion: v1
kind: Service
metadata:
  name: web-user-lb
  annotations: 
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: "35.202.170.17"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: web-user